apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    ENV: int
    app: avo2-proxy
    component: backend
  name: avo2-proxy-int
  namespace: sc-avo2

spec:
  replicas: 1
  selector:
    ENV: int
    app: avo2-proxy
    component: backend
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        git-branch: master
      creationTimestamp: null
      labels:
        ENV: int
        app: avo2-proxy
        component: backend
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: proxy-int
          image: >-
            docker-registry.default.svc:5000/sc-avo2/avo2-proxy@sha256:9784b9bbe8f60681bf182804298a86b36e8ccc1bce1b323b19a4dab2ef8a29ce
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 12
            
          imagePullPolicy: Always
          name: avo2-proxy-int
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
      terminationGracePeriodSeconds: 10
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - avo2-proxy-int
        from:
          kind: ImageStreamTag
          name: 'avo2-proxy:int'
          namespace: sc-avo2
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/sc-avo2/avo2-proxy@sha256:9784b9bbe8f60681bf182804298a86b36e8ccc1bce1b323b19a4dab2ef8a29ce
      type: ImageChange
    - type: ConfigChange

